import { createHmac, timingSafeEqual } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import type { Pool } from 'pg';
import { z } from 'zod';
import { CryptoGatewayAdapter } from '@inrliquid/adapters';
import { createCryptoGatewayWalletPayment } from './payments.js';

function verify(raw:string,signature:string|undefined,secret:string|undefined){if(!signature||!secret)return false;const expected=createHmac('sha256',secret).update(raw,'utf8').digest('hex');const supplied=signature.replace(/^sha256=/,'');const a=Buffer.from(expected),b=Buffer.from(supplied);return a.length===b.length&&timingSafeEqual(a,b);}

export async function registerCryptoRoutes(app:FastifyInstance,pool:Pool,gateway:CryptoGatewayAdapter|null){
 app.post('/v1/payments/crypto/intents',async(request,reply)=>{const parsed=z.object({amountUsd:z.number().positive().finite(),asset:z.string().trim().toUpperCase().min(2).max(20),network:z.string().trim().toUpperCase().min(2).max(30),idempotencyKey:z.string().min(16).max(128)}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_CRYPTO_PAYMENT',issues:parsed.error.issues});if(!gateway)return reply.code(503).send({error:'CRYPTO_UNAVAILABLE',message:'Crypto gateway is not configured'});const rate=Number(process.env.CRYPTO_USD_INR_RATE??0);if(!Number.isFinite(rate)||rate<=0)return reply.code(503).send({error:'CRYPTO_UNAVAILABLE',message:'CRYPTO_USD_INR_RATE is not configured'});if(process.env.ALLOW_DEV_USER_HEADER!=='true')return reply.code(401).send({error:'AUTH_PROVIDER_REQUIRED'});const header=request.headers['x-user-id'];if(typeof header!=='string'||!z.string().uuid().safeParse(header).success)return reply.code(401).send({error:'AUTH_REQUIRED'});try{return reply.code(201).send(await createCryptoGatewayWalletPayment(pool,header,parsed.data.amountUsd,parsed.data.amountUsd*rate,parsed.data.asset,parsed.data.network,parsed.data.idempotencyKey,gateway));}catch(error){return reply.code(503).send({error:'CRYPTO_UNAVAILABLE',message:String(error)});}});
 app.post('/v1/webhooks/crypto',{config:{rawBody:true}},async(request,reply)=>{const raw=String((request as typeof request&{rawBody?:string}).rawBody??'');if(!verify(raw,request.headers['x-crypto-signature'] as string|undefined,process.env.CRYPTO_GATEWAY_WEBHOOK_SECRET))return reply.code(401).send({error:'INVALID_CRYPTO_WEBHOOK_SIGNATURE'});const event=z.object({paymentId:z.string().min(1),status:z.enum(['CONFIRMED','FAILED','EXPIRED']),txHash:z.string().min(1).optional(),confirmations:z.number().int().min(0).optional()}).safeParse(JSON.parse(raw));if(!event.success)return reply.code(400).send({error:'INVALID_CRYPTO_WEBHOOK',issues:event.error.issues});const client=await pool.connect();try{await client.query('BEGIN');const intent=await client.query(`SELECT * FROM payment_intents WHERE provider='crypto' AND provider_payment_id=$1 FOR UPDATE`,[event.data.paymentId]);if(intent.rows[0]){const row=intent.rows[0];const tx=await client.query(`SELECT * FROM wallet_transactions WHERE provider='crypto' AND provider_transaction_id=$1 FOR UPDATE`,[event.data.paymentId]);if(event.data.status==='CONFIRMED'&&row.status!=='COMPLETED'){await client.query(`UPDATE payment_intents SET status='COMPLETED',completed_at=now(),metadata=metadata || $1 WHERE id=$2`,[JSON.stringify({txHash:event.data.txHash,confirmations:event.data.confirmations??0}),row.id]);if(tx.rows[0]?.status==='PENDING'){await client.query(`UPDATE wallet_transactions SET status='COMPLETED',completed_at=now(),metadata=metadata || $1 WHERE id=$2`,[JSON.stringify({txHash:event.data.txHash,confirmations:event.data.confirmations??0}),tx.rows[0].id]);await client.query(`UPDATE wallet_accounts SET available_paise=available_paise+$1,updated_at=now() WHERE id=$2`,[row.amount_paise,row.wallet_id]);}}else if(['FAILED','EXPIRED'].includes(event.data.status)&&['PENDING','PROCESSING','CREATED'].includes(row.status)){await client.query(`UPDATE payment_intents SET status=$1,completed_at=now(),metadata=metadata || $2 WHERE id=$3`,[event.data.status,event.data,row.id]);if(tx.rows[0]?.status==='PENDING')await client.query(`UPDATE wallet_transactions SET status='FAILED',completed_at=now() WHERE id=$1`,[tx.rows[0].id]);}}await client.query('COMMIT');return reply.send({ok:true});}catch(error){await client.query('ROLLBACK');throw error}finally{client.release();}});
}
