import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import { createStripeCryptoPaymentIntent, createStripePaymentIntent, CryptoGatewayAdapter, type StripeConfig } from '@inrliquid/adapters';

async function walletFor(client: PoolClient, userId: string) {
  const result = await client.query(`INSERT INTO wallet_accounts(id,user_id) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET updated_at=now() RETURNING id`, [randomUUID(), userId]);
  return result.rows[0];
}

export async function createStripeWalletPayment(pool:Pool,userId:string,amountInr:number,method:'card'|'upi',idempotencyKey:string,config:StripeConfig){
  const amountPaise=Math.round(amountInr*100),client=await pool.connect();
  try{await client.query('BEGIN');const existing=await client.query(`SELECT * FROM payment_intents WHERE idempotency_key=$1 FOR UPDATE`,[idempotencyKey]);if(existing.rows[0]){await client.query('COMMIT');return existing.rows[0];}const wallet=await walletFor(client,userId),intentId=randomUUID(),txId=randomUUID(),providerMethod=method==='card'?'CARD':'UPI';await client.query(`INSERT INTO payment_intents(id,user_id,wallet_id,provider,payment_method,amount_paise,status,idempotency_key,metadata) VALUES($1,$2,$3,'stripe',$4,$5,'PENDING',$6,$7)`,[intentId,userId,wallet.id,providerMethod,amountPaise,idempotencyKey,JSON.stringify({idempotencyKey})]);await client.query(`INSERT INTO wallet_transactions(id,wallet_id,type,status,amount_paise,provider,idempotency_key,metadata) VALUES($1,$2,'DEPOSIT','PENDING',$3,'stripe',$4,$5)`,[txId,wallet.id,amountPaise,`stripe:${idempotencyKey}`,JSON.stringify({paymentIntentId:intentId,method:providerMethod})]);await client.query('COMMIT');try{const payment=await createStripePaymentIntent(config,{amountInr,idempotencyKey,method,metadata:{wallet_transaction_id:txId,payment_intent_id:intentId}});await pool.query(`UPDATE payment_intents SET provider_payment_id=$1,client_secret=$2,metadata=metadata || $3::jsonb WHERE id=$4`,[payment.providerPaymentId,payment.clientSecret??null,JSON.stringify(payment),intentId]);await pool.query(`UPDATE wallet_transactions SET provider_transaction_id=$1,metadata=metadata || $2::jsonb WHERE id=$3`,[payment.providerPaymentId,JSON.stringify(payment),txId]);return{paymentIntentId:intentId,transactionId:txId,payment};}catch(error){await pool.query(`UPDATE payment_intents SET status='FAILED',completed_at=now(),metadata=metadata || $1::jsonb WHERE id=$2`,[JSON.stringify({providerError:String(error)}),intentId]);await pool.query(`UPDATE wallet_transactions SET status='FAILED',completed_at=now() WHERE id=$1`,[txId]);throw error;}}catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}}

export async function createStripeCryptoWalletPayment(pool:Pool,userId:string,amountUsd:number,targetInr:number,asset:string,network:string,idempotencyKey:string,config:StripeConfig){
  const amountPaise=Math.round(targetInr*100),client=await pool.connect();
  try{await client.query('BEGIN');const existing=await client.query(`SELECT * FROM payment_intents WHERE idempotency_key=$1 FOR UPDATE`,[idempotencyKey]);if(existing.rows[0]){await client.query('COMMIT');return existing.rows[0];}const wallet=await walletFor(client,userId),intentId=randomUUID(),txId=randomUUID();await client.query(`INSERT INTO payment_intents(id,user_id,wallet_id,provider,payment_method,asset,network,amount_paise,settlement_amount_minor,settlement_currency,status,idempotency_key,metadata) VALUES($1,$2,$3,'stripe','CRYPTO',$4,$5,$6,$7,'USD','PENDING',$8,$9)`,[intentId,userId,wallet.id,asset,network,amountPaise,Math.round(amountUsd*100),idempotencyKey,JSON.stringify({asset,network,amountUsd,targetInr})]);await client.query(`INSERT INTO wallet_transactions(id,wallet_id,type,status,amount_paise,provider,idempotency_key,metadata) VALUES($1,$2,'DEPOSIT','PENDING',$3,'stripe',$4,$5)`,[txId,wallet.id,amountPaise,`stripe:${idempotencyKey}`,JSON.stringify({paymentIntentId:intentId,method:'CRYPTO',asset,network,amountUsd})]);await client.query('COMMIT');try{const payment=await createStripeCryptoPaymentIntent(config,{amountUsd,idempotencyKey,asset,network});await pool.query(`UPDATE payment_intents SET provider_payment_id=$1,client_secret=$2,metadata=metadata || $3::jsonb WHERE id=$4`,[payment.providerPaymentId,payment.clientSecret??null,JSON.stringify(payment),intentId]);await pool.query(`UPDATE wallet_transactions SET provider_transaction_id=$1,metadata=metadata || $2::jsonb WHERE id=$3`,[payment.providerPaymentId,JSON.stringify(payment),txId]);return{paymentIntentId:intentId,transactionId:txId,payment,targetInr};}catch(error){await pool.query(`UPDATE payment_intents SET status='FAILED',completed_at=now(),metadata=metadata || $1::jsonb WHERE id=$2`,[JSON.stringify({providerError:String(error)}),intentId]);await pool.query(`UPDATE wallet_transactions SET status='FAILED',completed_at=now() WHERE id=$1`,[txId]);throw error;}}catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}}

export async function createCryptoGatewayWalletPayment(pool:Pool,userId:string,amountUsd:number,_targetInr:number,asset:string,network:string,idempotencyKey:string,gateway:CryptoGatewayAdapter){
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    const existing=await client.query(`SELECT * FROM payment_intents WHERE idempotency_key=$1 FOR UPDATE`,[idempotencyKey]);
    if(existing.rows[0]){await client.query('COMMIT');return existing.rows[0];}
    const wallet=await walletFor(client,userId),intentId=randomUUID(),txId=randomUUID();
    await client.query('COMMIT');

    const payment=await gateway.createPayment({amountUsd,asset,network,idempotencyKey,reference:intentId,settlementCurrency:'INR'});
    if(payment.quotedInr===undefined||!Number.isFinite(payment.quotedInr)||payment.quotedInr<=0) throw new Error('CRYPTO_GATEWAY_MISSING_INR_QUOTE');
    const amountPaise=Math.round(payment.quotedInr*100);
    if(amountPaise<=0) throw new Error('CRYPTO_GATEWAY_INVALID_INR_QUOTE');

    const db=await pool.connect();
    try{
      await db.query('BEGIN');
      const race=await db.query(`SELECT * FROM payment_intents WHERE idempotency_key=$1 FOR UPDATE`,[idempotencyKey]);
      if(race.rows[0]){await db.query('COMMIT');await gateway.cancelPayment(payment.providerPaymentId).catch(()=>undefined);return race.rows[0];}
      await db.query(`INSERT INTO payment_intents(id,user_id,wallet_id,provider,payment_method,asset,network,amount_paise,settlement_amount_minor,settlement_currency,status,idempotency_key,metadata,deposit_address,payment_url,quoted_rate,provider_fee_minor) VALUES($1,$2,$3,'crypto','CRYPTO',$4,$5,$6,$7,'USD','PENDING',$8,$9,$10,$11,$12,$13)`,[intentId,userId,wallet.id,asset,network,amountPaise,Math.round(amountUsd*100),idempotencyKey,JSON.stringify({amountUsd,quotedInr:payment.quotedInr,asset,network}),payment.depositAddress,payment.paymentUrl??null,payment.quotedRate??(payment.quotedInr/amountUsd),payment.providerFeeUsd===undefined?null:Math.round(payment.providerFeeUsd*100)]);
      await db.query(`INSERT INTO wallet_transactions(id,wallet_id,type,status,amount_paise,provider,idempotency_key,metadata) VALUES($1,$2,'DEPOSIT','PENDING',$3,'crypto',$4,$5)`,[txId,wallet.id,amountPaise,`crypto:${idempotencyKey}`,JSON.stringify({paymentIntentId:intentId,asset,network,amountUsd,quotedInr:payment.quotedInr})]);
      await db.query(`UPDATE payment_intents SET provider_payment_id=$1,metadata=metadata || $2::jsonb WHERE id=$3`,[payment.providerPaymentId,JSON.stringify(payment),intentId]);
      await db.query(`UPDATE wallet_transactions SET provider_transaction_id=$1,metadata=metadata || $2::jsonb WHERE id=$3`,[payment.providerPaymentId,JSON.stringify(payment),txId]);
      await db.query('COMMIT');
      return{paymentIntentId:intentId,transactionId:txId,payment,targetInr:payment.quotedInr};
    }catch(error){try{await db.query('ROLLBACK')}catch{}await gateway.cancelPayment(payment.providerPaymentId).catch(()=>undefined);throw error}finally{db.release()}
  }catch(error){try{await client.query('ROLLBACK')}catch{}throw error}finally{client.release()}
}

export async function settleStripeWebhook(pool:Pool,event:Record<string,any>){const object=event.data?.object,providerId=String(object?.id??'');if(!providerId)return;const client=await pool.connect();try{await client.query('BEGIN');const intent=await client.query(`SELECT * FROM payment_intents WHERE provider='stripe' AND provider_payment_id=$1 FOR UPDATE`,[providerId]);if(!intent.rows[0]){await client.query('ROLLBACK');return;}const row=intent.rows[0],tx=await client.query(`SELECT * FROM wallet_transactions WHERE provider='stripe' AND provider_transaction_id=$1 FOR UPDATE`,[providerId]);if(event.type==='payment_intent.succeeded'&&row.status!=='SUCCEEDED'){await client.query(`UPDATE payment_intents SET status='SUCCEEDED',completed_at=now() WHERE id=$1`,[row.id]);if(tx.rows[0]?.status==='PENDING'){await client.query(`UPDATE wallet_transactions SET status='COMPLETED',completed_at=now() WHERE id=$1`,[tx.rows[0].id]);await client.query(`UPDATE wallet_accounts SET available_paise=available_paise+$1,updated_at=now() WHERE id=$2`,[row.amount_paise,row.wallet_id]);}}if(['payment_intent.payment_failed','payment_intent.canceled'].includes(event.type)&&['PENDING','PROCESSING','CREATED'].includes(row.status)){await client.query(`UPDATE payment_intents SET status=$1,completed_at=now() WHERE id=$2`,[event.type.endsWith('canceled')?'CANCELED':'FAILED',row.id]);if(tx.rows[0]?.status==='PENDING')await client.query(`UPDATE wallet_transactions SET status='FAILED',completed_at=now() WHERE id=$1`,[tx.rows[0].id]);}await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
