import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { UpstoxAdapter } from '@inrliquid/adapters';
import type { BrokerAdapter, CreateOrderRequest, CreateTpSlRequest, OrderReceipt } from '@inrliquid/domain';
import { decryptSecret } from './token-crypto.js';

function unavailable(message: string): never { throw new Error(message); }
async function brokerForUser(pool: Pool, userId: string): Promise<{ broker: UpstoxAdapter; accountId: string; providerAccountId: string }> { const result = await pool.query(`SELECT id,provider,provider_account_id,access_token_encrypted,status FROM broker_accounts WHERE user_id=$1 AND status='ACTIVE' LIMIT 1`, [userId]); const account = result.rows[0]; if (!account) unavailable('BROKER_ACCOUNT_NOT_LINKED'); if (account.provider !== 'upstox') unavailable('BROKER_PROVIDER_UNSUPPORTED'); if (!account.access_token_encrypted) unavailable('BROKER_ACCESS_TOKEN_MISSING'); const accessToken = decryptSecret(account.access_token_encrypted); const raw = process.env.UPSTOX_INSTRUMENT_MAP_JSON; if (!raw) unavailable('UPSTOX_INSTRUMENT_MAP_NOT_CONFIGURED'); let instrumentMap: Record<string, string>; try { instrumentMap = JSON.parse(raw) as Record<string, string>; } catch { unavailable('UPSTOX_INSTRUMENT_MAP_INVALID'); } return { broker: new UpstoxAdapter({ accessToken, orderBaseUrl: process.env.UPSTOX_ORDER_BASE_URL, marketBaseUrl: process.env.UPSTOX_MARKET_BASE_URL, instrumentMap }), accountId: account.id, providerAccountId: account.provider_account_id }; }
function receiptStatus(status: OrderReceipt['status']): string { return status === 'ACCEPTED' ? 'OPEN' : status === 'REJECTED' ? 'REJECTED' : 'PENDING'; }
async function recordEvent(pool: Pool, orderId: string, eventType: string, receipt: OrderReceipt, payload: Record<string, unknown> = {}) { await pool.query(`INSERT INTO order_events(id,order_id,event_type,provider_status,payload) VALUES($1,$2,$3,$4,$5)`, [randomUUID(), orderId, eventType, receipt.status, JSON.stringify({ ...payload, providerOrderId: receipt.providerOrderId, acceptedAt: receipt.acceptedAt })]); }
function clientOrderId(input: { clientOrderId?: string; idempotencyKey: string }): string { return input.clientOrderId ?? `inrliquid-${input.idempotencyKey}`; }
export async function listUserOrders(pool: Pool, userId: string, limit = 100) { const result = await pool.query(`SELECT id,client_order_id,provider,provider_order_id,exchange,symbol,side,order_type,quantity,limit_price,trigger_price,time_in_force,status,filled_quantity,average_fill_price,rejection_reason,metadata,created_at,updated_at,completed_at FROM orders WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2`, [userId, Math.min(Math.max(limit,1),200)]); return result.rows; }

async function persistPendingOrder(pool: Pool, args: { orderId: string; userId: string; accountId: string; clientId: string; exchange: string; symbol: string; side: string; orderType: string; quantity: number; limitPrice: number|null; triggerPrice: number|null; timeInForce: string; metadata: Record<string, unknown> }) {
  const inserted = await pool.query(`INSERT INTO orders(id,user_id,broker_account_id,client_order_id,provider,exchange,symbol,side,order_type,quantity,limit_price,trigger_price,time_in_force,status,metadata) VALUES($1,$2,$3,$4,'upstox',$5,$6,$7,$8,$9,$10,$11,$12,'PENDING',$13) ON CONFLICT(user_id,client_order_id) DO NOTHING RETURNING id`, [args.orderId,args.userId,args.accountId,args.clientId,args.exchange,args.symbol,args.side,args.orderType,args.quantity,args.limitPrice,args.triggerPrice,args.timeInForce,JSON.stringify(args.metadata)]);
  if (inserted.rowCount) return { id: args.orderId, created: true };
  const existing = await pool.query(`SELECT * FROM orders WHERE user_id=$1 AND client_order_id=$2`, [args.userId,args.clientId]);
  if (!existing.rows[0]) throw new Error('ORDER_IDEMPOTENCY_RACE');
  return { id: existing.rows[0].id, created: false, existing: existing.rows[0] };
}

export async function placeUserOrder(pool: Pool, userId: string, input: CreateOrderRequest) { const clientId = clientOrderId(input); const { broker, accountId } = await brokerForUser(pool, userId); const pending = await persistPendingOrder(pool,{orderId:randomUUID(),userId,accountId,clientId,exchange:input.exchange,symbol:input.symbol,side:input.side,orderType:input.orderType,quantity:input.quantity,limitPrice:input.limitPriceInr??null,triggerPrice:input.triggerPriceInr??null,timeInForce:input.timeInForce,metadata:{reduceOnly:input.reduceOnly,postOnly:input.postOnly,parentOrderId:input.parentOrderId??null,ocoGroupId:input.ocoGroupId??null}}); if (!pending.created) return { ...pending.existing, idempotent:true }; const orderId = pending.id; let receipt: OrderReceipt; try { receipt = await broker.placeOrder(input); } catch (error) { await pool.query(`UPDATE orders SET status='UNKNOWN',rejection_reason=$1,updated_at=now() WHERE id=$2`, [String(error), orderId]); await pool.query(`INSERT INTO order_events(id,order_id,event_type,provider_status,payload) VALUES($1,$2,'provider_error','UNKNOWN',$3)`, [randomUUID(),orderId,JSON.stringify({message:String(error)})]); throw new Error('ORDER_SUBMISSION_AMBIGUOUS'); } const status=receiptStatus(receipt.status); await pool.query(`UPDATE orders SET provider_order_id=$1,status=$2,rejection_reason=$3,updated_at=now(),completed_at=CASE WHEN $2='REJECTED' THEN now() ELSE NULL END WHERE id=$4`,[receipt.providerOrderId||null,status,status==='REJECTED'?'PROVIDER_REJECTED':null,orderId]); await recordEvent(pool,orderId,'provider_submission',receipt); return {id:orderId,clientOrderId:clientId,providerOrderId:receipt.providerOrderId,status:receipt.status,acceptedAt:receipt.acceptedAt,idempotent:false}; }

export async function placeUserTpSl(pool: Pool, userId: string, input: CreateTpSlRequest) { const clientId=`tpsl-${input.idempotencyKey}`; const { broker, accountId }=await brokerForUser(pool,userId); const orderId=randomUUID(); const orderType=input.kind==='TP'?(input.market?'TAKE_MARKET':'TAKE_LIMIT'):(input.market?'STOP_MARKET':'STOP_LIMIT'); const pending=await persistPendingOrder(pool,{orderId,userId,accountId,clientId,exchange:input.exchange,symbol:input.symbol,side:input.side,orderType,quantity:input.quantity,limitPrice:input.limitPriceInr??null,triggerPrice:input.triggerPriceInr,timeInForce:'GTC',metadata:{kind:input.kind,reduceOnly:true,parentOrderId:input.parentOrderId??null,ocoGroupId:input.ocoGroupId??null}}); if(!pending.created)return {...pending.existing,idempotent:true}; let receipt:OrderReceipt; try{receipt=await broker.placeTpSl(input);}catch(error){await pool.query(`UPDATE orders SET status='UNKNOWN',rejection_reason=$1,updated_at=now() WHERE id=$2`,[String(error),orderId]);await pool.query(`INSERT INTO order_events(id,order_id,event_type,provider_status,payload) VALUES($1,$2,'provider_error','UNKNOWN',$3)`,[randomUUID(),orderId,JSON.stringify({message:String(error)})]);throw error;} const status=receiptStatus(receipt.status); await pool.query(`UPDATE orders SET provider_order_id=$1,status=$2,rejection_reason=$3,updated_at=now(),completed_at=CASE WHEN $2='REJECTED' THEN now() ELSE NULL END WHERE id=$4`,[receipt.providerOrderId||null,status,status==='REJECTED'?'PROVIDER_REJECTED':null,orderId]);await recordEvent(pool,orderId,'provider_submission',receipt,{kind:input.kind});return {id:orderId,clientOrderId:clientId,providerOrderId:receipt.providerOrderId,status:receipt.status,acceptedAt:receipt.acceptedAt,idempotent:false}; }

export async function modifyUserOrder(pool: Pool,userId:string,localOrderId:string,input:CreateOrderRequest){const result=await pool.query(`SELECT * FROM orders WHERE id=$1 AND user_id=$2`,[localOrderId,userId]);const order=result.rows[0];if(!order)throw new Error('ORDER_NOT_FOUND');if(!order.provider_order_id)throw new Error('ORDER_PROVIDER_ID_MISSING');if(!['PENDING','OPEN','PARTIALLY_FILLED'].includes(order.status))throw new Error('ORDER_NOT_MODIFIABLE');const {broker}=await brokerForUser(pool,userId);const receipt=await broker.modifyOrder(order.provider_order_id,input);const updated=await pool.query(`UPDATE orders SET quantity=$1,limit_price=$2,trigger_price=$3,status=$4,updated_at=now(),version=version+1 WHERE id=$5 AND version=$6`,[input.quantity,input.limitPriceInr??null,input.triggerPriceInr??null,receiptStatus(receipt.status),localOrderId,order.version]);if(!updated.rowCount)throw new Error('ORDER_VERSION_CONFLICT');await recordEvent(pool,localOrderId,'provider_modify',receipt);return {id:localOrderId,providerOrderId:order.provider_order_id,status:receipt.status,acceptedAt:receipt.acceptedAt};}
export async function cancelUserOrder(pool: Pool,userId:string,localOrderId:string){const result=await pool.query(`SELECT * FROM orders WHERE id=$1 AND user_id=$2`,[localOrderId,userId]);const order=result.rows[0];if(!order)throw new Error('ORDER_NOT_FOUND');if(!order.provider_order_id)throw new Error('ORDER_PROVIDER_ID_MISSING');if(!['PENDING','OPEN','PARTIALLY_FILLED'].includes(order.status))throw new Error('ORDER_NOT_CANCELABLE');const {broker}=await brokerForUser(pool,userId);await broker.cancelOrder(order.provider_order_id);const updated=await pool.query(`UPDATE orders SET status='CANCELED',updated_at=now(),completed_at=now(),version=version+1 WHERE id=$1 AND version=$2 AND status IN ('PENDING','OPEN','PARTIALLY_FILLED')`,[localOrderId,order.version]);if(!updated.rowCount)throw new Error('ORDER_VERSION_CONFLICT');await pool.query(`INSERT INTO order_events(id,order_id,event_type,provider_status,payload) VALUES($1,$2,'provider_cancel','CANCELED',$3)`,[randomUUID(),localOrderId,JSON.stringify({providerOrderId:order.provider_order_id})]);}
function mapProviderStatus(value:unknown):string{const s=String(value??'').toLowerCase().replace(/_/g,' ');if(s.includes('complete')||s==='filled')return 'FILLED';if(s.includes('partial'))return 'PARTIALLY_FILLED';if(s.includes('cancel'))return 'CANCELED';if(s.includes('reject'))return 'REJECTED';if(s.includes('expire'))return 'EXPIRED';if(s.includes('open')||s.includes('trigger')||s.includes('received')||s.includes('pending'))return 'OPEN';return 'UNKNOWN';}
export async function applyUpstoxOrderWebhook(pool:Pool,payload:Record<string,unknown>){if(payload.update_type!=='order')return {ignored:true};const providerOrderId=String(payload.order_id??'');const providerAccountId=String(payload.user_id??payload.userId??payload.placed_by??'');if(!providerOrderId||!providerAccountId)return {ignored:true};const orderResult=await pool.query(`SELECT o.* FROM orders o JOIN broker_accounts b ON b.id=o.broker_account_id WHERE o.provider='upstox' AND o.provider_order_id=$1 AND b.provider_account_id=$2 LIMIT 1`,[providerOrderId,providerAccountId]);const order=orderResult.rows[0];if(!order)return {ignored:true,reason:'ORDER_NOT_FOUND'};const eventId=`upstox:${providerOrderId}:${String(payload.order_request_id??'')}:${String(payload.status??'')}:${String(payload.order_timestamp??'')}:${String(payload.filled_quantity??'')}`;const inserted=await pool.query(`INSERT INTO order_events(id,order_id,provider_event_id,event_type,provider_status,filled_quantity,average_fill_price,payload) VALUES($1,$2,$3,'webhook',$4,$5,$6,$7) ON CONFLICT(provider_event_id) DO NOTHING`,[randomUUID(),order.id,eventId,String(payload.status??''),Number(payload.filled_quantity??0),Number(payload.average_price??0)||null,JSON.stringify(payload)]);if(!inserted.rowCount)return {duplicate:true};const status=mapProviderStatus(payload.status);const filled=Number(payload.filled_quantity??0);const avg=Number(payload.average_price??0)||null;await pool.query(`UPDATE orders SET status=$1,filled_quantity=$2,average_fill_price=COALESCE($3,average_fill_price),last_provider_event_at=now(),updated_at=now(),completed_at=CASE WHEN $1 IN ('FILLED','CANCELED','REJECTED','EXPIRED') THEN now() ELSE completed_at END,version=version+1 WHERE id=$4`,[status,filled,avg,order.id]);return {applied:true,orderId:order.id,status};}

function tradeQuantity(trade: Record<string, unknown>): number { return Number(trade.quantity ?? trade.traded_quantity ?? 0); }
function tradePrice(trade: Record<string, unknown>): number { return Number(trade.traded_price ?? trade.average_price ?? trade.price ?? 0); }
function tradeId(trade: Record<string, unknown>): string { return String(trade.trade_id ?? trade.id ?? trade.order_ref_id ?? ''); }
function tradeTime(trade: Record<string, unknown>): string { return String(trade.exchange_timestamp ?? trade.order_timestamp ?? new Date().toISOString()); }

export async function reconcileUserOrders(pool: Pool, userId: string, limit = 50) {
  const { broker } = await brokerForUser(pool, userId);
  const result = await pool.query(`SELECT id,provider_order_id,status,version FROM orders WHERE user_id=$1 AND provider='upstox' AND provider_order_id IS NOT NULL AND status IN ('UNKNOWN','PENDING','OPEN','PARTIALLY_FILLED') ORDER BY updated_at ASC LIMIT $2`, [userId, Math.min(Math.max(limit, 1), 100)]);
  let reconciled = 0; let fills = 0;
  for (const order of result.rows) {
    const history = await broker.getOrderHistory(order.provider_order_id);
    const latest = history.at(-1) ?? history[0];
    if (latest) {
      const status = mapProviderStatus(latest.status);
      const filled = Number(latest.filled_quantity ?? 0);
      const average = Number(latest.average_price ?? 0) || null;
      await pool.query(`UPDATE orders SET status=$1,filled_quantity=$2,average_fill_price=COALESCE($3,average_fill_price),rejection_reason=CASE WHEN $1='REJECTED' THEN $4 ELSE rejection_reason END,last_provider_event_at=now(),updated_at=now(),completed_at=CASE WHEN $1 IN ('FILLED','CANCELED','REJECTED','EXPIRED') THEN now() ELSE completed_at END,version=version+1 WHERE id=$5`, [status, filled, average, String(latest.status_message ?? 'PROVIDER_REJECTED'), order.id]);
      await pool.query(`INSERT INTO order_events(id,order_id,provider_event_id,event_type,provider_status,filled_quantity,average_fill_price,payload) VALUES($1,$2,$3,'reconciliation',$4,$5,$6,$7) ON CONFLICT(provider_event_id) DO NOTHING`, [randomUUID(), order.id, `upstox:reconcile:${order.provider_order_id}:${String(latest.order_timestamp ?? '')}:${String(latest.status ?? '')}:${filled}`, String(latest.status ?? ''), filled, average, JSON.stringify(latest)]);
      reconciled += 1;
    }
    const providerTrades = await broker.getOrderTrades(order.provider_order_id);
    for (const trade of providerTrades) {
      const providerTradeId = tradeId(trade); const quantity = tradeQuantity(trade); const price = tradePrice(trade);
      if (!providerTradeId || quantity <= 0 || price <= 0) continue;
      const inserted = await pool.query(`INSERT INTO trade_fills(id,order_id,provider_trade_id,quantity,price,fee,executed_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(order_id,provider_trade_id) DO NOTHING`, [randomUUID(), order.id, providerTradeId, quantity, price, Number(trade.fee ?? 0) || null, tradeTime(trade), JSON.stringify(trade)]);
      if (inserted.rowCount) fills += 1;
    }
  }
  return { reconciled, fills, checked: result.rows.length };
}
